# Generated by Django 3.1.1 on 2020-09-22 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20200922_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='cart_id',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='delete',
        ),
    ]
