# Generated by Django 3.1.1 on 2020-09-20 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'colors',
            },
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.CharField(max_length=50, null=True)),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.color')),
            ],
            options={
                'db_table': 'thumbnails',
            },
        ),
        migrations.RemoveField(
            model_name='thumnail',
            name='thumnail_url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='thumnail_url',
        ),
        migrations.DeleteModel(
            name='Order_Product',
        ),
        migrations.DeleteModel(
            name='Thumnail',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='product_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
