# Generated by Django 3.1.1 on 2020-09-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thumbnail',
            old_name='product_title',
            new_name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(through='products.Thumbnail', to='products.Color'),
        ),
        migrations.AlterField(
            model_name='color',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
