# Generated by Django 3.1.1 on 2020-09-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200920_0744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='additional_feature',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_banner',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_key_feature',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_note',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_teaser',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='specs_details',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
