# Generated by Django 3.1.1 on 2020-09-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200923_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='image_url',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
