# Generated by Django 3.1.1 on 2020-09-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200920_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_key_feature',
            field=models.TextField(null=True),
        ),
    ]
