# Generated by Django 3.1.1 on 2020-09-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200920_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='thumbnail_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
