# Generated by Django 3.1.1 on 2020-09-20 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200920_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.color'),
        ),
    ]
